export const getAppTitle = () => cy.get('#apples-title');
export const getApples = () => cy.get('.apple');
export const getRedApples = () => cy.get('.apple.red');
export const getGreenApples = () => cy.get('.apple.green');
export const getAddOneAppleButton = () => cy.get('#add-one-apple');
export const getAddRedAppleButton = () => cy.get('#add-red-apple');
export const getAddGreenAppleButton = () => cy.get('#add-green-apple');
export const getRemoveRedApplesButton = () => cy.get('#remove-red-apples');
export const getRemoveGreenApplesButton = () => cy.get('#remove-green-apples');
